// Generated by Wrangler on Wed Jun 26 2024 21:43:07 GMT+0800 (Malaysia Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	BASE_URL: "http://localhost:3000";
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	API_TOKEN: string;
	DB: D1Database;
}
