// Generated by Wrangler on Sat Jun 29 2024 14:16:20 GMT+0800 (Malaysia Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	BASE_URL: "http://localhost:3000";
	EMAIL_SERVER_URL: "https://email-server.sisheng.my";
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	API_TOKEN: string;
	DB: D1Database;
}
