// Generated by Wrangler on Mon Jun 17 2024 22:00:41 GMT+0800 (Malaysia Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	BASE_URL: "http://localhost:3000";
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	DB: D1Database;
}
