#:schema node_modules/wrangler/config-schema.json
name = "wallet"
compatibility_date = "2024-06-03"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
BASE_URL = "http://localhost:3000"
EMAIL_SERVER_URL = "https://email-server.sisheng.my"

[[d1_databases]]
binding = "DB"
database_name = "wallet"
database_id = "a7b156d3-2473-46a4-b1cb-a9635fa77a94"
migrations_dir = "src/db/migrations"

######## PRODUCTION environment config ########

[env.production.vars]
BASE_URL = "https://wallet.sisheng.my"
EMAIL_SERVER_URL = "https://email-server.sisheng.my"

[[env.production.d1_databases]]
binding = "DB"
database_name = "wallet"
database_id = "a7b156d3-2473-46a4-b1cb-a9635fa77a94"
migrations_dir = "src/db/migrations"